In [21]:
a=int(input("value:"))
s=1243
su=a+s
j=su+s
rt=s**a
ui="asdfghjk"
print("power:",rt)
print(su)
print("add: ",j)
print(input("name"))

value:4
power: 2387176412401
1247
add:  2490
namey
y


In [28]:
print("string:",ui,"integer:",s)

string: asdfghjk integer: 1243


In [13]:
w="jhwejk"
d='hwej'
print(w+" "+d)

jhwejk hwej


In [32]:
p=34
t=45
print(type(p))
print("before:",p,t)
temp=0
temp=p
p=t
t=temp
print("after:",p,t)

<class 'int'>
before: 34 45
after: 45 34


In [1]:
""" 
p,t=t,p
print(p,t)"""

' \np,t=t,p\nprint(p,t)'

In [9]:
s="ich bin waser"
s[4]+s[9:12]


'base'

In [11]:
a=12
c=14
print("before:",a,c)
a,c=c,a
print("after:",a,c)

before: 12 14
after: 14 12


In [39]:
s=[122,132,"eat","team","term"]
print(s[-1]+" "+s[-2]+" "+s[-3])
a=[132,241,243,1341,411,113,1,2]
a.sort()
print(a)
min(a)
max(a)

term team eat
[1, 2, 113, 132, 241, 243, 411, 1341]


1341

In [44]:
s[2],s[-1]=s[-1],s[2]
s

[122, 132, 'term', 'team', 'eat']

In [96]:
q=[]
q.append(8)
print(q)



q.extend(q)
print(q)
q[0],q[1]=78,3
print(q)
q.pop()
print(q)

[8]
[8, 8]
[78, 3]
[78]


In [102]:
qw=[232,32,4,1,5,1]
print(qw[1]**qw[-2])
print("this is list:",qw)
er=tuple(qw)
print(er[1]+er[-2])

33554432
this is list: [232, 32, 4, 1, 5, 1]
37


In [115]:
#keys values
d={1:"name",5:"age",9:"id","year":1990}
#print(d[1])
#print(d[5])
#print(d[9])
d["time"]=12
#print(d.keys())
#print(d.values())
print(d)

{1: 'name', 5: 'age', 9: 'id', 'year': 1990, 'time': 12}


In [119]:
""" member ship opertors  in not in 
identity ope   is  not """

lst1=["yash","shiva"]
a=input("value:")
a in lst1

value:team


False

In [125]:
ae=input("value1")
ah=input("value1")
ae is ah

value1yu
value1yu


False

In [126]:
ae=int(input("value1"))
ah=int(input("value2"))
ae is ah

value12
value212


False

In [3]:
x=int(input("input number:"))
s=[12,1,31,33,45]
d=["a","b","c"]
if x in s:
    print("value is in list")
    
else:
    print("not in list")

input number:12
value is in list


In [ ]:
and or not
& | ^
hex
oct
bin

In [20]:
print(bin(123))
print(hex(123))   
print(oct(123))  
print((bin(1)+oct(123)+hex(12)))
print(2^1)
print(2&1)
print((2|1))
print(~-6)


0b1111011
0x7b
0o173
0b10o1730xc
3
0
3
5


In [ ]:
if condition:
    if condition:
        if condition:
elif condition:
    
else:
    if :
        if :
            
        else:
            
    print()

In [25]:
for i in range(2,11,2):  #range(1,n-1,diff)
    print(i)

2
4
6
8
10


In [27]:
for i in "python":
    print(i)

p
y
t
h
o
n


In [35]:
x=[12,1,43]
for i in range(len(x)):
    print("index:",i,"----->value:",x[i])

index: 0 ----->value: 12
index: 1 ----->value: 1
index: 2 ----->value: 43


In [75]:
r=[]
st=[r]
df=[st]
for i in range(1,6):
    df.append(i)
    st.append(i)
    r.append(i)
print(df)    

[[[1, 2, 3, 4, 5], 1, 2, 3, 4, 5], 1, 2, 3, 4, 5]


In [69]:
st=[]
df=[st]
for i in range(1,4):
    print
    for i in range(df)

print(df) 
for i in df:
    print(i)

[[], [], [], [], [], [], [], [], [], []]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [12]:
x=int(input("enetr value"))
n=int(input("range"))
even=[]
odd=[]
while x<=n:
    if x%2==0:
        even.append(x)
    else:
        odd.append(x)
    x+=1
    else:
        print("condition is not true----->VALUE NOT VALID")
print(even)
print(odd)

enetr value1
range9
condition is not true----->VALUE NOT VALID
[2, 4, 6, 8]
[1, 3, 5, 7, 9]


Parameterized and unParameterized functions
Argument,default,lambda function-map,list,reduce,filter
arbitrary variable,recursive function

In [4]:
def calc():
    a=int(input("value1:"))
    b=int(input("value1:"))
    add=a+b
    print("addition:",add)
    sub=a-b
    print("subtract:",sub)
    p=a**b
    print("power:",p)

In [5]:
calc()

value1:3
value1:3
addition: 6
subtract: 0
power: 27


In [6]:
def a():
    print("print1")
def b():
    calc()
    a()
    print("print2")

In [7]:
b()

value1:2
value1:3
addition: 5
subtract: -1
power: 8
print1
print2


In [9]:
def a(s):
    print("additiion",s+s)
def b(t):
    a(int(input("value")))
    print("multi:",t*t)

In [10]:
b(int(input("value")))

value23
value2
additiion 4
multi: 529


In [11]:
b(5)

value4
additiion 8
multi: 25


In [12]:
a(6)

additiion 12


In [16]:
def add(a,b=12,work="LAB"):
    print("addition:",a+b,)
def sub(a,b=11):
    print("subtraction:",a-b)

In [19]:
add(2)

addition: 14


In [20]:
sub(3)

subtraction: -8


In [57]:
def ad(a,*b):
    print(a)
    print(b)
    for i in b:
        i+=i
        print(i)

In [58]:
ad(12,234,2435,52,2)

12
(234, 2435, 52, 2)
468
4870
104
4


In [59]:
cube=lambda x:x*x
print(cube(3))

9


In [60]:
area=lambda x,y:x*y
print(area(3,6))

18


In [61]:
ar=lambda x,y,r,t:x*y**r/t
print(ar(3,6,5,3))

    

7776.0


In [62]:
def calci():
    ar=lambda x,y,r,t:x*y**r/t
    print(ar(3,6,5,3))
    
    ar=lambda x,y,r,t:x*y**r/t
    print(ar(3,6,5,3))
    

In [74]:
w=[1,2,3,4]
w1=[1,2,3,4]
#map(fucnt,list)
jk=zip(w,w1)
print(list(jk))
print(list(map(lambda x,y:x/y,w,w1)))
print(list(map(lambda x,y:x-y,w,w1)))
print(list(map(lambda x,y:x*y,w,w1)))

[(1, 1), (2, 2), (3, 3), (4, 4)]
[1.0, 1.0, 1.0, 1.0]
[0, 0, 0, 0]
[1, 4, 9, 16]


In [92]:
list1=[]
def a(s):
    print("additiion",s+s)
    list1.append(a)
def b(t):
    print("multi:",t*t)
    list1.append(a)

In [93]:
#list1.append(a)
#list1.append(b)
list1

[]

In [79]:
print(list1[0])

<function a at 0x0000020086499730>


In [88]:
list1=[a(23),b(29),a(2),b(9)]

additiion 46
multi: 841
additiion 4
multi: 81


In [91]:
for i in list1:
    list1[i]()

TypeError: list indices must be integers or slices, not NoneType

In [94]:
e=["abc"]
e.append(a)

In [101]:
print(e[0])
print(e[1](3))

abc
additiion 6
None


In [102]:
a(9)

additiion 18


In [104]:
print(a)

<function a at 0x00000200864B7048>


In [1]:
a()
list1[0]()

NameError: name 'a' is not defined

In [4]:
w=[1,2,3,4]
import functools as f
list1=f.reduce(lambda a,b:a+b,w)
print(list1)

10


In [5]:
import functools as f
def ad(a,*b):
        list1=f.reduce(lambda a,c:a+c,b)
        print(list1)

In [6]:
ad(2,23,23,34,5,6)

91


In [9]:
def ad(a,*b):
        list1=f.reduce(lambda x,y:x if x>y else y,b)
        print(list1)

In [11]:
ad(2,23,23,34,5)

34


In [12]:
def ad(a,*b):
        list1=f.reduce(lambda x,y:x if x<y else y,b)
        print(list1)

In [13]:
ad(2,23,23,34,5)

5


In [19]:
sum[x,x*x for i in range(1,20)]

SyntaxError: invalid syntax (<ipython-input-19-be5e63ae8504>, line 1)

In [21]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [23]:
math.cos(0)

1.0

In [24]:
math.cos(90)

-0.4480736161291701

In [25]:
math.factorial(6)

720

In [27]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

In [30]:
import statistics as sp

In [32]:
dir(statistics)
help(sp)

Help on module statistics:

NAME
    statistics - Basic statistics module.

DESCRIPTION
    This module provides functions for calculating statistics of data, including
    averages, variance, and standard deviation.
    
    Calculating averages
    --------------------
    
    ==================  =============================================
    Function            Description
    ==================  =============================================
    mean                Arithmetic mean (average) of data.
    harmonic_mean       Harmonic mean of data.
    median              Median (middle value) of data.
    median_low          Low median of data.
    median_high         High median of data.
    median_grouped      Median, or 50th percentile, of grouped data.
    mode                Mode (most common value) of data.
    ==================  =============================================
    
    Calculate the arithmetic mean ("the average") of data:
    
    >>> mean([-1.0, 2.5, 3.25, 

In [48]:
import string as st
st.ascii_lowercase
st.ascii_uppercase
s=st.capwords("qweuuuuuuu")

In [49]:
s.capitalize()

'Qweuuuuuuu'

In [50]:
s.count("u")

7

In [57]:
s.upper()
s.lower()

'qweuuuuuuu'

In [2]:
import time as t
t.sleep
import termcolor as tp
print(tp.colored("string","red"))
t.sleep(2)
print(tp.colored("string","yellow"))
t.sleep(2)
print(tp.colored("string","magenta"))
t.sleep(2)
print(tp.colored("string","green"))
print(tp.colored("string","cyan"))
print(tp.colored("string","blue"))
print(tp.colored("string","white"))

string
string
string
string
string
string
string


In [4]:
list2=[1,0,1,8]
list3=[1,1,9,0]
orout=[]
andout=[]
xorout=[]
def andgate():
    
    for i in  range(len(list3)):
        team=list2[i] & list3[i]
        orout.append(team)
        time.sleep(2)
        print("----->",team)
        
def orgate():
    
    for i in  range(len(list3)):
        team=list2[i] | list3[i]
        andout.append(team)
        time.sleep(2)
        print("---->",team)
        
        
def xorgate():
    
    for i in  range(len(list3)):
        team=list2[i] ^ list3[i]
        xorout.append(team)
        time.sleep(2)
        print("---->",team)

In [5]:
import time
print("                  WELCOME TO LOGIC TRAIN                ")
print("OR GATE",orout)
orgate()
print("AND GATE",andout)
andgate()
print("XOR GATE",xorout)

xorgate()

                  WELCOME TO LOGIC TRAIN                
OR GATE []
----> 1
----> 1
----> 9
----> 8
AND GATE [1, 1, 9, 8]
-----> 1
-----> 0
-----> 1
-----> 0
XOR GATE []
----> 0
----> 1
----> 8
----> 8


In [20]:
list1=[1,2,3,4,5,6]
import numpy as np
arr=np.asarray(list1)
print(arr)
arr3=arr.shape


arr1=arr.reshape(2,3)
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [35]:
arr2=arr.reshape(1,6)
print(arr2.shape)
at=arr2.T
print(at)
print(at.shape)
orr=at.reshape(1,-1)
list1.reverse
print(list1)

(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[6, 5, 4, 3, 2, 1]


In [31]:
import  termcolor as tp
arr5=arr.reshape(2,3)
print(arr5)
print(tp.colored(arr5[0][1]+arr5[0][0],"red"))
print(tp.colored(arr5[...,1],"magenta"))
print(arr5[...,1])
print(arr5[0,...])

[[1 2 3]
 [4 5 6]]
3
[2 5]
[2 5]
[1 2 3]


In [38]:
class airvehi():
    def bomb(self):
        print("drop the bomb")
    def airgun(self):
        print("fire - fire")
        
        
class roadvehi():
    def nitors(self):
        print("boost of the car")
    def jetengine(self):
        print("jet engine installed")
    
    

In [41]:
obj=airvehi()
obj.bomb()
obj.airgun()

drop the bomb
fire - fire


In [42]:
obj1=roadvehi()
obj1.jetengine()
obj1.nitors()

jet engine installed
boost of the car


In [1]:
class calc1():
    def add(self,a,b):
        print("adding",a+b)
    def sub(self,a,b):
        print("subtarct",a-b)
        
        
class calc2():
    def mult(self,a,b):
        print("multilication",a*b)
    def div(self,a,b):
        print("division",a/b)
    
    

In [2]:
obj1=calc1()
obj1.add(23,45)

adding 68


In [3]:
class calc3():
    def __init__(self,a,b):  #constructor and instance variable declaration
        self.a=a
        self.b=b
    def mult(self):
        print("multilication",self.a*self.b)
    def div(self):
        print("division",self.a/self.b)
    

In [5]:
obj2=calc3(2,3)
obj2.mult()
obj2.div()

multilication 6
division 0.6666666666666666


In [6]:
for i in range(1,3):
    obj2=calc3(int(input("ist value:")),int(input("2nd value:")))
    obj2.mult()
    obj2.div()

ist value:12
2nd value:3
multilication 36
division 4.0
ist value:132
2nd value:45
multilication 5940
division 2.933333333333333


In [7]:
class calc4():
    def __init__(self,a,b=67):  #constructor and instance variable declaration
        self.a=a
        self.b=b
    def mult(self):
        print("multilication",self.a*self.b)
    def div(self):
        print("division",self.a/self.b)
    

In [8]:
obj2=calc4(2) #default constructor----b value is set as default value
obj2.mult()
obj2.div()

multilication 134
division 0.029850746268656716


In [9]:
obj2=calc4(2,8) #default constructor----b value is set as default value
obj2.mult()
obj2.div()

multilication 16
division 0.25


In [12]:
class calc7():
    def add(self,a,*b):
        lt=list(map(lambda x:x*x,b))
        print(lt)
        

In [13]:
obj7=calc7()
obj7.add(1,2,3,4,5,6)

[4, 9, 16, 25, 36]


In [18]:
class calc7():
    def __init__(self,a,*b):
        self.a=a
        self.b=b
    def add(self):
        lt=list(map(lambda x:x*x,self.b))
        print(lt*self.a)
        print(self.a)
        

In [19]:
obj8=calc7(2,2,3,4,5,6)
obj8.add()

[4, 9, 16, 25, 36, 4, 9, 16, 25, 36]
2


In [21]:
class calc1():
    def add(self,a,b):
        print("adding",a+b)
    def sub(self,a,b):
        print("subtarct",a-b)
        
        
class calc2(calc1):
    def mult(self,a,b):
        print("multilication",a*b)
    def div(self,a,b):
        print("division",a/b)
    
    
import math    
class calc3(calc2):
    def pwr(self,a,b):
        print("power",a**b)
    def sqt(self,a,b):
        print("square root",math.sqrt(a/b))
    

In [24]:
obj9=calc3()
obj9.div(12,3)
obj9.mult(12,3)
obj9.pwr(12,3)
obj9.sqt(12,3)
obj9.sub(12,3)
obj9.add(12,3)

division 4.0
multilication 36
power 1728
square root 2.0
subtarct 9
adding 15


In [25]:
class calc1():
    def add(self,a,b):
        print("adding",a+b)
    def sub(self,a,b):
        print("subtarct",a-b)
        
        
class calc2():
    def mult(self,a,b):
        print("multilication",a*b)
    def div(self,a,b):
        print("division",a/b)
    
    
import math    
class calc3():
    def pwr(self,a,b):
        print("power",a**b)
    def sqt(self,a,b):
        print("square root",math.sqrt(a/b))

class infoc(calc1,calc2,calc3):
    print("calc1----calc2-----calc3")

calc1----calc2-----calc3


In [26]:
oj=infoc()
oj.div(12,3)
oj.mult(12,3)
oj.pwr(12,3)
oj.sqt(12,3)
oj.sub(12,3)
oj.add(12,3)

division 4.0
multilication 36
power 1728
square root 2.0
subtarct 9
adding 15


In [9]:
#polymorphism

class h():
    def calc(self,a):
        f=a**a
        print("value multiply:",f)
        

class t():
    def calc(self,a):
        f=a*a
        print("value of powewr:",f)        

In [10]:
obj12=h()
obj12.calc(3)
obj13=t()
obj13.calc(3)

value multiply: 27
value of powewr: 9


In [28]:
#method overiding

class h():
    def calc(self):
        print("value multiply:👌")
    def sel(self):
        print("BIKING:🐱‍🏍")   
class t(h):
    def calc(self):
        print("value multiply:👌")
    def calc(self):
    
        print("value of powewr:👍")        
    def calc(self):
        print("value multiply:👌")

In [29]:
objk=t()
#objk1=h()
#objk1.calc()
objk.calc()
objk.sel()

value multiply:👌
BIKING:🐱‍🏍


In [7]:
print("haste rhao lol","😀😂🤣")

haste rhao lol 😀😂🤣


In [5]:

for i i
o=input("enetr ur mood")
print(o)

enetr ur moodchal nikal😂
chal nikal😂


In [13]:
w="😀😂🤣"*3
print(w)

😀😂🤣😀😂🤣😀😂🤣


In [14]:
d=["😀","😂","🤣"]
for i in d:
    print(i)

😀
😂
🤣


In [44]:
#data encapusaltion

class kyt():
    def __init__(self,a,b,f):
        self.a=a  #publib
        self.__b=b  #private
        self._f=f  #protected
    def info(self):
        print(self.a)
        print(self.__b)
        print(self._f)

In [45]:
obk=kyt(1,2,5)

In [47]:
obk.info()

1
2
5


In [48]:
obk.a

1

In [49]:
obk._f

5

In [51]:
obk._kyt__b

2

In [ ]:
class __xyz():
    def sub():
        
    def __add():
        

In [9]:
import re
f=open("test_speech.txt","r")
print(f.read())
for i in range(1,3):
    f=open("test_speech.txt","r")
    x=input("enter the word to search:")
    y=re.findall(x,f.read())
    print(y)
    print(y.count(x))

When he spoke to the Democratic National Convention in support of Senator John Kerry, 
the party’s presidential nominee against George W. Bush,
 Barack Obama was an obscure state senator running for the US Senate. 
His soaring speech made the case for putting aside partisan differences and bringing Americans together; 
it also introduced him to the country and meant that he was instantly tipped to become a future president.

“We worship an awesome God in the blue states and we don’t like federal agents
 poking around in our libraries in the Red States.
enter the word to search:is
['is', 'is']
2
enter the word to search:t
['t', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't', 't']
44


In [10]:
import urllib as ur
ur.request("")

In [11]:
dir(urllib)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'error',
 'parse',
 'request',
 'response']

In [9]:
list1=["🎱","✂","📝"]
list1[0]
for i in list1:
    print(i)
        

🎱
✂
📝


In [14]:
list1=["🎱","✂","📝"]
for i in list1:
    print(list1[0])
    print(list1[1])
    print(list1[2])

🎱
✂
📝
🎱
✂
📝
🎱
✂
📝


In [10]:
print(i[0])

📝


In [11]:
i[-1]

'📝'

In [18]:
list1=["🎱","✂","📝"]

for i in list1:
    print(list1)
    x=input("enetr your choice:")
    x1=input("enetr your choice:")
    if x==list1[0]:
        print("---->stone wins",list1[0])
        
    elif x1==list1[1]:
        print("----->scissor wins",list1[1])
        
    else:
        print("--------> paper wins",list1[2])
    

['🎱', '✂', '📝']
enetr your choice:'📝'
enetr your choice:'📝'
--------> paper wins 📝
['🎱', '✂', '📝']
enetr your choice:'✂'
enetr your choice:'✂'
--------> paper wins 📝
['🎱', '✂', '📝']
enetr your choice:'🎱'
enetr your choice:'🎱'
--------> paper wins 📝


In [23]:
#iterators
e=[1,2,3,4]
u=iter(e)

c=next(u)
print(c)
c=next(u)
print(c)
c=next(u)
print(c)
c=next(u)
print(c)
c=next(u)
print(c)

1
2
3
4


StopIteration: 

In [25]:
f=[1,2,3,4,5]
uw=iter(f)
while True:
    try:
        c=next(uw)
        print(c)
    
    except:
        
        print("stop iteration")
        break

1
2
3
4
5
stop iteration


In [35]:
f=[1,2,3,4,5]
uw=iter(f)
while True:
        c=next(uw)
        print(c)
        if c==None:
            print("list is empty")
        
  

1
2
3
4
5


StopIteration: 

In [48]:
f=[1,2,3,4,5]
uw=iter(f)
while True:
    if next(uw)==None:
            print(next
    else:
        print(c)
         
  

5
5
5
5
5


StopIteration: 

ModuleNotFoundError: No module named 'puz'

In [33]:
#generators

def a():
    n=3
    yield n
    
    n=n+1
    yield n
    
    
    
    n=2*n
    yield n
  
    n=n/8
    yield n

In [34]:
for i in a():
    print(i)

3
4
8
1.0
